### ISSUE TITLE
Can't login in Void Linux

### ISSUE THREAD

**Issue by systemd7** [flathub/com.spotify.Client#155]
After i install when i run flatpak run com.spotify.Client open the Spotify client but when i click login just load "Redirecting to browser to complete login" and never opens the browser

Here's the output of flatpak run com.spotify.Client
```
[system@void ~]$ /app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
[spotifywm] attached to spotify
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[spotifywm] attached to spotify
[spotifywm] attached to spotify
/proc/self/exe: /app/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[spotifywm] spotify window found
[spotifywm] attached to spotify
```

**Comment by vercinstex** [comment]
different output if I run from command line but same result, I click LOGIN but spotify do not open the browser.

> After i install when i run flatpak run com.spotify.Client open the Spotify client but when i click login just load "Redirecting to browser to complete login" and never opens the browser

flatpak run com.spotify.Client
$ /app/extra/bin/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
[spotifywm] attached to spotify
/app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[spotifywm] attached to spotify
[spotifywm] attached to spotify
Gtk-Message: 22:04:02.982: Failed to load module "xapp-gtk3-module"
Gtk-Message: 22:04:02.982: Failed to load module "xapp-gtk3-module"
Gtk-Message: 22:04:02.982: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:04:02.982: Failed to load module "canberra-gtk-module"
[spotifywm] spotify window 5800004 found
[spotifywm] spotify window 5600003 found
/proc/self/exe: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /proc/self/exe)
[spotifywm] spotify window 6000008 found
[spotifywm] attached to spotify

(spotify:6): GLib-GIO-WARNING **: 22:04:32.083: Cannot create document portal proxy: Errore nel chiamare StartServiceByName per org.freedesktop.portal.Desktop: È stato raggiunto il timeout
``

**Comment by edwargix** [comment]
same story here on Arch Linux
```
[~]$ flatpak run com.spotify.Client
[~]$ /app/extra/bin/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
[spotifywm] attached to spotify
/app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[spotifywm] attached to spotify
[spotifywm] attached to spotify
[spotifywm] spotify window 2c00004 found
[spotifywm] spotify window 2a00003 found
/proc/self/exe: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /proc/self/exe)
[spotifywm] attached to spotify
[spotifywm] spotify window 3200007 found
/app/bin/spotify: line 45: Xlib.xauth:: command not found
```

**Comment by miyurusankalpa** [comment]
I am getting the same error Fedora 39

```
$ flatpak info com.spotify.Client 

Spotify - Online music streaming service

          ID: com.spotify.Client
         Ref: app/com.spotify.Client/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.2.26.1187.g36b715a1
     License: LicenseRef-proprietary=https://www.spotify.com/us/legal/end-user-agreement/
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 9.3 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: d22ab2f6059cca52bc56754ca1860fb41b0d9c6333975bd8f2eb375fde5a4d84
      Parent: f2e534a3b5f444506de97d07d92535548f4cf222ae1d1fb4ff7680490b665934
     Subject: Update spotify.snap to 1.2.26.1187.g36b715a1 (b0d5128e)
        Date: 2023-12-15 17:53:17 +0000
```

might be related to #230

**Comment by Erick555** [comment]
curl is unrelated to this issue. This line is suspicious:
`/app/bin/spotify: line 45: Xlib.xauth:: command not found`

is it on wayland?

**Comment by miyurusankalpa** [comment]
> is it on wayland?

Yes.

Same issue on X11

```
$  flatpak run com.spotify.Client 
/app/extra/bin/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
[spotifywm] attached to spotify
/app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[spotifywm] attached to spotify
[spotifywm] attached to spotify
Gtk-Message: 04:16:18.264: Failed to load module "canberra-gtk-module"
Gtk-Message: 04:16:18.264: Failed to load module "pk-gtk-module"
Gtk-Message: 04:16:18.265: Failed to load module "canberra-gtk-module"
Gtk-Message: 04:16:18.265: Failed to load module "pk-gtk-module"
[spotifywm] spotify window 2800004 found
[spotifywm] spotify window 2400003 found
/proc/self/exe: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /proc/self/exe)
[spotifywm] attached to spotify
[spotifywm] spotify window 2e00007 found
[2023/12/23 04:16:19:3035] ERR: Couldn't identify address
[2023/12/23 04:16:19:9099] ERR: Couldn't identify address
[2023/12/23 04:16:20:3265] ERR: Couldn't identify address
```

**Comment by Erick555** [comment]
There is different error than above.

**Comment by edwargix** [comment]
> curl is unrelated to this issue. This line is suspicious: `/app/bin/spotify: line 45: Xlib.xauth:: command not found`
> 
> is it on wayland?

I am on wayland yes (sway, wlroots)

**Comment by xanedarel** [comment]
Have you tried installing these packages?
`xbps-install -Sy xdg-dbus-proxy xdg-desktop-portal xdg-desktop-portal-gtk ` 
Fixed it for me on KDE

**Comment by alkar** [comment]
Same here, spotify launches just fine but the login button won't do anything (assuming it's meant to open a browser window/tab for auth).

```
$ flatpak run com.spotify.Client --enable-features=UseOzonePlatform --ozone-platform=wayland
/app/extra/bin/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
[spotifywm] attached to spotify
/app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
Traceback (most recent call last):
  File "/app/bin/set-dark-theme-variant.py", line 11, in <module>
    disp = Xlib.display.Display()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.11/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Xlib/support/unix_connect.py", line 59, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
[spotifywm] attached to spotify
[spotifywm] attached to spotify

(spotify:7): Gdk-WARNING **: 18:36:13.811: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
/proc/self/exe: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /proc/self/exe)
[spotifywm] attached to spotify
```

Running arch & swaywm.

```
$ flatpak info com.spotify.Client

Spotify - Online music streaming service

          ID: com.spotify.Client
         Ref: app/com.spotify.Client/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.2.31.1205.g4d59ad7c
     License: LicenseRef-proprietary=https://www.spotify.com/us/legal/end-user-agreement/
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 17.3 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 9eb82ec8c70583f08d33590430ec1f5261c4f1105522e2b00bb209e9bc7b7fc1
      Parent: d2954f8a2628b86d676a6b8c43b385265ea9d978cf86974a52e6bc1d6be8669f
     Subject: Workaround: Create "spotify" directory in $XDG_CONFIG_HOME (6d81e535)
        Date: 2024-04-15 21:43:18 +0000
```
