### ISSUE TITLE
ERROR:web_plugin_impl.cc

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.spotify.Client#23]
```
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
/app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)
[1227/113942.653174:ERROR:proxy_config_service_linux.cc(274)] Error requesting gconf directory: Falha ao ativar servidor de configuração: org.freedesktop.DBus.Error.ServiceUnknown

[1227/114045.066812:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
```

**Comment by TingPing** [comment]
Is there an actual feature you use that isn't working?

**Comment by fbruetting** [comment]
Similar error at my system since a few weeks:
```
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
/proc/self/exe: /app/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[0525/172102.253057:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  set_option: Cannot assign requested address
Traceback (most recent call last):
  File "/app/bin/spotify", line 18, in <module>
    subprocess.check_call(argv)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/app/extra/bin/spotify', '--force-device-scale-factor=2.0']' returned non-zero exit status -6
```

**Comment by braceritchie** [comment]
@TingPing I'm not able to log in through proxy , similar error as @LeandroStanger

**Comment by fbruetting** [comment]
For me that went away some weeks ago… :)

**Comment by LeandroStanger** [comment]
```
/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
xprop: error: No window with name Spotify exists!
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /app/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[0806/200420.385484:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
[0806/200550.318829:ERROR:sandbox_ipc_linux.cc(447)] sendmsg: Broken pipe (32)
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 431, in __del__
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 58, in close
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 139, in remove_signal_handler
  File "/usr/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

**Comment by TingPing** [comment]
The printed errors aren't causing the problems and are unrelated. So I'll just close this so people stop bumping it.
