### ISSUE TITLE
Spotify crashes after update to Fedora 28

### ISSUE THREAD

**Issue by MartinBriza** [flathub/com.spotify.Client#30]
After updating to the last batched update in Fedora 28 yesterday (Tue Mar 13), flatpak'd Spotify started crashing for me consistently right after start. Before this update, it was fine. I can provide the list of updated packages upon request.

It's probably worth noting that negativo17's Spotify RPM for Fedora 27 works perfectly fine for me on this system.

```
$ rpm -q flatpak
flatpak-0.11.3-1.fc28.x86_64
```

```
$ flatpak info com.spotify.Client
Ref: app/com.spotify.Client/x86_64/master
ID: com.spotify.Client
Arch: x86_64
Branch: master
Origin: com.spotify.Client-2-origin
Date: 2017-07-21 12:17:16 +0000
Subject: Export com.spotify.Client
Commit: 16f9499d642bd5b408e77f83fc70732766c406a12dd43481d75b6139fdf7d79e
Parent: fb19586f2157fcc0c5ffa890793b17c0c23d34d86cdac1976dc57f060bcfb268
Location: /var/lib/flatpak/app/com.spotify.Client/x86_64/master/16f9499d642bd5b408e77f83fc70732766c406a12dd43481d75b6139fdf7d79e
Installed size: 19.3 MB
Runtime: org.gnome.Platform/x86_64/3.24
```

```
$ flatpak run com.spotify.Client   
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)                                                                                                   
Gtk-Message: Failed to load module "pk-gtk-module"                                                                                                                                                                 
/app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)                                                                               
/proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)                                                                                                                   
[0314/103706.446989:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain             
```

```
(gdb) run
Starting program: /app/extra/bin/spotify 
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
warning: File "/usr/lib/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
        add-auto-load-safe-path /usr/lib/libthread_db-1.0.so
line to your configuration file "/home/mbriza/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/mbriza/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
warning: File "/usr/lib/libstdc++.so.6.0.22-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
Gtk-Message: Failed to load module "pk-gtk-module"
[New LWP 9]
/app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[New LWP 11]
[New LWP 12]
[New LWP 13]
[New LWP 14]
[New LWP 15]
[New LWP 16]
[New LWP 17]
[New LWP 18]
[New LWP 19]
[New LWP 20]
[New LWP 21]
[New LWP 22]
[New LWP 23]
[New LWP 24]
[New LWP 25]
[New LWP 26]
[New LWP 27]
[New LWP 28]
[New LWP 29]
[New LWP 30]
/proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)
[New LWP 32]
[New LWP 34]
[New LWP 35]
[0314/103902.498119:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[New LWP 39]
[New LWP 40]
[New LWP 41]
[New LWP 42]
[New LWP 43]
[New LWP 44]

Thread 1 "spotify" received signal SIGSEGV, Segmentation fault.
0x00000000005f5d07 in ?? ()
(gdb) bt full
#0  0x00000000005f5d07 in  ()
#1  0x00000000005f5b81 in  ()
#2  0x00000000005f5d1d in  ()
#3  0x00000000015944df in  ()
#4  0x00007ffff0a5d415 in  () at /app/extra/share/spotify/libcef.so
#5  0x00007ffff1d0151b in  () at /app/extra/share/spotify/libcef.so
#6  0x00007ffff197acf5 in  () at /app/extra/share/spotify/libcef.so
#7  0x00007ffff18c1cb9 in  () at /app/extra/share/spotify/libcef.so
#8  0x00007ffff1df4fae in  () at /app/extra/share/spotify/libcef.so
#9  0x00007ffff1e10200 in  () at /app/extra/share/spotify/libcef.so
#10 0x00007ffff1e0fcf5 in  () at /app/extra/share/spotify/libcef.so
#11 0x00007ffff1e11999 in  () at /app/extra/share/spotify/libcef.so
#12 0x00007fffef95c1c7 in g_main_context_dispatch () at /lib/libglib-2.0.so.0
#13 0x00007fffef95c430 in  () at /lib/libglib-2.0.so.0
#14 0x00007fffef95c4dc in g_main_context_iteration () at /lib/libglib-2.0.so.0
#15 0x00007ffff1e11bf6 in  () at /app/extra/share/spotify/libcef.so
#16 0x00007ffff1e2d0c0 in  () at /app/extra/share/spotify/libcef.so
#17 0x00007ffff1d0e1c8 in  () at /app/extra/share/spotify/libcef.so
#18 0x0000000001583389 in  ()
#19 0x00000000005d547e in  ()
#20 0x00000000005d4a69 in _start ()
```

**Comment by RobbiNespu** [comment]
It not just F28, it also happened on F27
```bash
$ flatpak install --from https://flathub.org/repo/appstream/com.spotify.Client.flatpakref
Installing: com.spotify.Client/x86_64/stable
Updating: org.freedesktop.Platform.GL.nvidia-390-25/x86_64/1.4 from flathub
[####################] Downloading: 46.2 MB/46.2 MB (1.6 MB/s)                 
Now at dd835540ce45.
Installing: com.spotify.Client/x86_64/stable from flathub
[####################] Downloading: 101.1 MB/101.0 MB (261.3 kB/s)              

$ flatpak run --branch=stable --arch=x86_64 --command=spotify --file-forwarding com.spotify.Client  -v
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
/app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)
[0317/214629.575074:ERROR:proxy_config_service_linux.cc(274)] Error requesting gconf directory: Failed to activate configuration server: org.freedesktop.DBus.Error.ServiceUnknown
```
